"""
Just for the type checker to shut up
"""
from typing import Protocol

class TextStream(Protocol):
    def write(self, s: str) -> int: ...
    def flush(self) -> None: ...
    def isatty(self) -> bool: ...