"""
Just for the type checker to shut up
"""
from typing import Protocol

class TextStream(Protocol):
    def write(self, s: str) -> int: ...
    def flush(self) -> None: ...
    def isatty(self) -> bool: ...

# Dummy winpty for mypy to shut up about winpty on unix-like
class dummy_winpty:
    class PTY:
        def __init__(self, *args, **kwargs): ...
        
        def spawn(self, *args, **kwargs): ...
        
        def write(self, *args, **kwargs): ...